"""Searchable NSE stock universe for the dashboard picker (symbol -> company name).

NIFTY 100 + liquid midcaps/popular names. The picker also accepts ANY symbol
typed by the user - this list only powers the search suggestions.
"""

STOCK_UNIVERSE = {
    "RELIANCE": "Reliance Industries", "TCS": "Tata Consultancy Services",
    "HDFCBANK": "HDFC Bank", "ICICIBANK": "ICICI Bank", "INFY": "Infosys",
    "SBIN": "State Bank of India", "BHARTIARTL": "Bharti Airtel",
    "HINDUNILVR": "Hindustan Unilever", "ITC": "ITC", "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen & Toubro", "AXISBANK": "Axis Bank", "MARUTI": "Maruti Suzuki",
    "SUNPHARMA": "Sun Pharmaceutical", "TITAN": "Titan Company",
    "BAJFINANCE": "Bajaj Finance", "NESTLEIND": "Nestle India",
    "WIPRO": "Wipro", "ULTRACEMCO": "UltraTech Cement", "HCLTECH": "HCL Technologies",
    "ASIANPAINT": "Asian Paints", "M&M": "Mahindra & Mahindra",
    "ADANIENT": "Adani Enterprises", "ADANIPORTS": "Adani Ports",
    "TATAMOTORS": "Tata Motors", "TATASTEEL": "Tata Steel", "POWERGRID": "Power Grid",
    "NTPC": "NTPC", "ONGC": "ONGC", "COALINDIA": "Coal India",
    "BAJAJFINSV": "Bajaj Finserv", "TECHM": "Tech Mahindra", "LTIM": "LTIMindtree",
    "HDFCLIFE": "HDFC Life Insurance", "SBILIFE": "SBI Life Insurance",
    "DIVISLAB": "Divi's Laboratories", "CIPLA": "Cipla", "DRREDDY": "Dr Reddy's Labs",
    "GRASIM": "Grasim Industries", "JSWSTEEL": "JSW Steel", "HINDALCO": "Hindalco",
    "BRITANNIA": "Britannia Industries", "EICHERMOT": "Eicher Motors",
    "HEROMOTOCO": "Hero MotoCorp", "BAJAJ-AUTO": "Bajaj Auto", "TATACONSUM": "Tata Consumer",
    "APOLLOHOSP": "Apollo Hospitals", "INDUSINDBK": "IndusInd Bank",
    "BPCL": "Bharat Petroleum", "IOC": "Indian Oil", "HPCL": "Hindustan Petroleum",
    "SHRIRAMFIN": "Shriram Finance", "CHOLAFIN": "Cholamandalam Finance",
    "PIDILITIND": "Pidilite Industries", "SIEMENS": "Siemens", "ABB": "ABB India",
    "DLF": "DLF", "GODREJPROP": "Godrej Properties", "OBEROIRLTY": "Oberoi Realty",
    "PRESTIGE": "Prestige Estates", "HAVELLS": "Havells India", "DABUR": "Dabur India",
    "MARICO": "Marico", "GODREJCP": "Godrej Consumer", "COLPAL": "Colgate-Palmolive",
    "BERGEPAINT": "Berger Paints", "AMBUJACEM": "Ambuja Cements", "ACC": "ACC",
    "SHREECEM": "Shree Cement", "DALBHARAT": "Dalmia Bharat",
    "VEDL": "Vedanta", "SAIL": "SAIL", "NMDC": "NMDC", "JINDALSTEL": "Jindal Steel",
    "HAL": "Hindustan Aeronautics", "BEL": "Bharat Electronics", "BDL": "Bharat Dynamics",
    "BHARATFORG": "Bharat Forge", "MAZDOCK": "Mazagon Dock", "COCHINSHIP": "Cochin Shipyard",
    "IRCTC": "IRCTC", "RVNL": "RVNL", "IRFC": "IRFC", "IRCON": "IRCON International",
    "TITAGARH": "Titagarh Rail Systems", "INDIGO": "InterGlobe Aviation (IndiGo)",
    "SPICEJET": "SpiceJet", "TATAPOWER": "Tata Power", "ADANIGREEN": "Adani Green Energy",
    "ADANIPOWER": "Adani Power", "SUZLON": "Suzlon Energy", "INOXWIND": "Inox Wind",
    "WAAREEENER": "Waaree Energies", "EXIDEIND": "Exide Industries",
    "ARE&M": "Amara Raja Energy", "OLECTRA": "Olectra Greentech", "SERVOTECH": "Servotech Power",
    "MUTHOOTFIN": "Muthoot Finance", "MANAPPURAM": "Manappuram Finance",
    "PAYTM": "Paytm (One97)", "ZOMATO": "Zomato (Eternal)", "NYKAA": "Nykaa (FSN)",
    "POLICYBZR": "PB Fintech (PolicyBazaar)", "DMART": "Avenue Supermarts (DMart)",
    "TRENT": "Trent (Westside/Zudio)", "JUBLFOOD": "Jubilant FoodWorks (Domino's)",
    "VBL": "Varun Beverages", "UNITDSPR": "United Spirits", "UBL": "United Breweries",
    "PAGEIND": "Page Industries (Jockey)", "TRIDENT": "Trident", "KPRMILL": "KPR Mill",
    "AUROPHARMA": "Aurobindo Pharma", "LUPIN": "Lupin", "ZYDUSLIFE": "Zydus Lifesciences",
    "BIOCON": "Biocon", "ALKEM": "Alkem Laboratories", "TORNTPHARM": "Torrent Pharma",
    "MAXHEALTH": "Max Healthcare", "FORTIS": "Fortis Healthcare", "LALPATHLAB": "Dr Lal PathLabs",
    "GMRINFRA": "GMR Airports", "NBCC": "NBCC India", "NCC": "NCC",
    "KNRCON": "KNR Constructions", "IRB": "IRB Infrastructure",
    "BHEL": "BHEL", "CUMMINSIND": "Cummins India", "THERMAX": "Thermax",
    "POLYCAB": "Polycab India", "KEI": "KEI Industries", "DIXON": "Dixon Technologies",
    "AMBER": "Amber Enterprises", "VOLTAS": "Voltas", "BLUESTARCO": "Blue Star",
    "WHIRLPOOL": "Whirlpool India", "CROMPTON": "Crompton Greaves Consumer",
    "ASHOKLEY": "Ashok Leyland", "ESCORTS": "Escorts Kubota", "TVSMOTOR": "TVS Motor",
    "MOTHERSON": "Samvardhana Motherson", "BOSCHLTD": "Bosch", "MRF": "MRF",
    "APOLLOTYRE": "Apollo Tyres", "CEATLTD": "CEAT", "BALKRISIND": "Balkrishna Industries",
    "IDEA": "Vodafone Idea", "INDUSTOWER": "Indus Towers", "TATACOMM": "Tata Communications",
    "ICICIPRULI": "ICICI Prudential Life", "LICI": "LIC of India",
    "ICICIGI": "ICICI Lombard", "PNB": "Punjab National Bank", "BANKBARODA": "Bank of Baroda",
    "CANBK": "Canara Bank", "UNIONBANK": "Union Bank", "IDFCFIRSTB": "IDFC First Bank",
    "FEDERALBNK": "Federal Bank", "AUBANK": "AU Small Finance Bank", "YESBANK": "Yes Bank",
    "CHAMBLFERT": "Chambal Fertilisers", "COROMANDEL": "Coromandel International",
    "GNFC": "GNFC", "UPL": "UPL", "PIIND": "PI Industries", "SRF": "SRF",
    "DEEPAKNTR": "Deepak Nitrite", "TATACHEM": "Tata Chemicals",
    "BALRAMCHIN": "Balrampur Chini", "TRIVENI": "Triveni Engineering",
    "OIL": "Oil India", "GAIL": "GAIL", "PETRONET": "Petronet LNG", "IGL": "Indraprastha Gas",
    "MGL": "Mahanagar Gas", "GUJGASLTD": "Gujarat Gas", "CONCOR": "Container Corporation",
    "DELHIVERY": "Delhivery", "INDHOTEL": "Indian Hotels (Taj)", "EIHOTEL": "EIH (Oberoi Hotels)",
}
